* airy

*airy* is a command line Python script to read a [[https://www2.purpleair.com][PurpleAir]] sensor reading via PurpleAir's REST API. 

#+BEGIN_SRC plantuml :file doc/images/airy-architecture.svg
participant User
participant "airy.db" as db
participant airy
participant PurpleAir

User -> airy: airy.py <sensorID>
airy -> PurpleAir: GET https://www.purpleair.com/json?show=<sensorID>
airy <-- PurpleAir: OK: JSON for <sensorID>

#+END_SRC

#+RESULTS:
[[file:doc/images/airy-architecture.svg]]


* Features

- Command line interface to support automation.
- Storage of /PurpleAir/ sensor readings are stored in [[https://www.sqlite.org/index.html][SQLite]] 3 database.
- SMS alert support to be notified when AQI has gotten worse or better.
   - Requires [[https://www.twilio.com][Twilio]] SMS service

* Example

#+BEGIN_SRC sh
$ ./airy.py 60015
Airy SensorID: 60015
    Raw PM2.5: 9.96   -10.4%
    EPA PM2.5: 41
 AQ & U PM2.5: 43
      Level 0: Good. Air quality is considered satisfactory.
#+END_SRC


* How to use

TBD

* Requirements

TBD


* TL;DR Installation

In the top level directory `airy` execute the following commands:

#+BEGIN_SRC sh
$ make venv
$ source venv/bin/activate
$ make install-dependencies
#+END_SRC


* License

Copyright 2020 Charles Y. Choi

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.








